doctrine:
    dbal:
        driver: 'pdo_pgsql'
        server_version: '12'
        charset: utf8
        url: '%env(resolve:DATABASE_URL)%'

    orm:
        auto_generate_proxy_classes: false
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                mappings:
                    User:
                        is_bundle: false
                        type: xml
                        dir: '%kernel.project_dir%/src/Resources/doctrine/user'
                        prefix: 'App\Entity\User'
