version: "3"

services:
    postgres_test:
        image: "postgres:12"
        environment:
            POSTGRES_DB: "foo"
                POSTGRES_USER: "foo"
                POSTGRES_PASSWORD: "bar"
            PGDATA: "/var/lib/postgresql/data/pgdata"
            TZ: 'Europe/Paris'
            PGTZ: 'Europe/Paris'
        volumes:
            - "./docker/postgres/initdb.d/:/docker-entrypoint-initdb.d/"
        expose:
            - "5889"
        ports:
            - "5889:5432"
        networks:
            - "back"

networks:
    back:
        driver: bridge
